config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  post '/guest_sign_in', to: 'sessions#guest_sign_in'
  get '/signup', to: 'users#new'
  resources :users do
    member do
      get :posts, :liked
    end

    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        @micropost_new = Micropost.order(created_at: :desc).limit(5)
        @tags = ActsAsTaggableOn::Tag.most_used(10)
        if logged_in?
          @user = current_user
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <%= render partial: 'shared/user_info', locals: { user: @user } %>
    </div>

    <div class="col-md-10">
      <div class="container mb-2 top-bg" >
        <h3>総合新着作品</h3>
        <%= link_to '…もっと見る', microposts_path %>
        <div class="row justify-content-center">
          <%= render partial: 'shared/cards', locals: { microposts: @micropost_new } %>
        </div>
      </div>
      
      <div class="container mb-2 top-bg">
        <h3>人気タグTOP10</h3>
        <div class="row justify-content-center">
        <% @tags.each do |tag|%>
          <span class="badge badge-pill badge-primary mb-3 mr-3 p-2">
            <%= link_to tag.name, microposts_path(tag_name: tag.name), class: "text-white" %>
          </span>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_not_logged_in.html.erb
<div class="page-container">
  <div class="page-content">
    <h1 class="title">
      MangAnime
    </h1>
    <p class="content">
      <%= link_to '新規登録', signup_path %>
    </p>
    <p class="content">
      <%= link_to 'ログイン', login_path %>
    </p>
    <p class="content">
      <%= link_to 'ゲストログイン', guest_sign_in_path, method: :post %>
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <%= render 'logged_in'%>
<% else %>
    <%= render 'not_logged_in'%>
<% end %>