config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  post '/guest_sign_in', to: 'sessions#guest_sign_in'
  get '/signup', to: 'users#new'
  resources :users do
    member do
      get :posts, :liked
    end

    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end

end

app/views/shared/_cards.html.erb
<div class="row justify-content-center">
  <% microposts.each do |micropost| %>
    <div class="mx-2 mb-3">
      <div class="card my-2" style="width: 10rem;">
        <div class="card-image">
          <div class="d-flex flex-row m-1">
            <div class="user-image">
              <% if micropost.user.avatar.attached? %>
                <%= image_tag micropost.user.avatar %>
              <% else %>
                <%= image_tag '/assets/user_dummy.png' %>
              <% end%>
              <%= link_to micropost.user.name %>
            </div>
          </div>

          <% if micropost.images.attached? %>
            <div class="micropost-image img">
                <%= image_tag micropost.images %>
            </div>
          <% end%>

          <div class="card-body">
            <p class="card-text text-center">
              <%= link_to micropost_path(micropost) do %>
                <%= micropost.title %>
              <% end %>
            </p>
          </div>

          <div class="d-flex mb-1">
            <div class="ml-2">
              <i class="far fa-heart", style="color: #ff9aef;"></i>
              <%= micropost.likes.count %>
              <i class="far fa-comment" style="color: #6091d3;"></i>
              <%= micropost.comments.count %><br>
              <%= Date.parse(micropost.start_time.to_s).strftime("%Y年%m月%d日") %>
            </div> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class container>
  <p class="text-center">
    <% @users.each do |user| %>
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar, size: "30x30" %>
      <% else %>
        <%= image_tag '/assets/user_dummy.png', size: "30x30" %>
      <% end%>
      <%= link_to user.name, user %>
    <% end %>
  </p>
</div>

app/views/shared/_user_info.html.erb
<div class="container-fluid">
    <h3 class="text-center">プロフィール</h3>
    <p class="text-center">
      <%= link_to @user.name, user %>
    </p>
    <p class="text-center">
      <% if @user.avatar.attached? %>
        <%= image_tag user.avatar, size: "100x100" %>
      <% else %>
        <%= image_tag '/assets/user_dummy.png', size: "100x100" %>
      <% end%>
    </p>
    <p class="text-center">
      <%= link_to 'フォロー', user_follows_path(@user) %>
      <%= @user.follower.count %>
    </p>
    <p class="text-center">
      <%= link_to 'フォロワー', user_followers_path(@user) %>
      <%= @user.followed.count%>
    </p>
    <div class="text-center"> 
      <%= simple_format(@user.profile) %>
    </div>
</div>