config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  post '/guest_sign_in', to: 'sessions#guest_sign_in'
  get '/signup', to: 'users#new'
  resources :users do
    member do
      get :posts, :liked
    end

    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, length: { maximum: 120 }
  has_one_attached :images
  scope :recent_count, ->(count) { order(created_at: :desc).limit(count) }
  scope :recent, -> { order(id: :desc) }
  scope :current_month, -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :last_month, -> { where(created_at: Time.now.prev_month.beginning_of_month..Time.now.prev_month.end_of_month) }
  acts_as_taggable
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    def index
        if params[:tag_name]
            @microposts = Micropost.tagged_with(params[:tag_name].to_s)
            @tags = ActsAsTaggableOn::Tag.most_used(10)
        else
            @q = Micropost.ransack(params[:q])
            @microposts = @q.result(distinct: true)
        end
    end

    def show
        @micropost = Micropost.includes(:user).find(params[:id])
        @user = @micropost.user
        @comments = @micropost.comments.includes(:user).all
        @comment = Comment.new
    end

    def new
        @micropost = Micropost.new
    end

    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "投稿が完了しました"
            redirect_to @micropost
        else
            flash[:danger] = "投稿に失敗しました"
            render :new
        end
    end

    def edit
        @micropost = Micropost.find(params[:id])
    end

    def update
        @micropost = Micropost.find(params[:id])
        if @micropost.update(micropost_params)
            redirect_to micropost_path(@micropost), notice: '投稿を更新しました。'
        else
            flash.now[:alert] = '入力に誤りがあります。'
            render :edit
        end
    end

    def destroy
        @micropost = Micropost.find(params[:id])
        @micropost.destroy
        flash[:success] = '投稿を削除しました。'
        redirect_to root_url
    end

    private

    def micropost_params
        params.require(:micropost).permit(:content, :title, :start_time, :tag_list, :images)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/edit.html.erb
<h1 class="text-center">投稿編集</h1>

<div class="edit-container">
  <div class="edit-items">
    <%= form_with model: @micropost, local: true do |form| %>
    <div class="form-group">
      <%= form.label :start_time, "日付" %><br>
      <%= form.datetime_select :start_time %>
    </div>
    <div class="form-group">
      <%= form.label :title, "タイトル" %><br>
      <%= form.text_field :title, class: "form-control border border-primary" %>
    </div>
    <div class="form-group">
        <%= form.label :images, "画像"%><br>
        <%= form.file_field :images, accept: "image/png, image/jpeg, image/gif", class: "form-control border border-primary", multiple: true %>
      </div>
    <div class="form-group">
      <%= form.label :content, "詳細" %><br>
      <%= form.text_area :content, class: "form-control border border-primary"%>
    </div>
    <div class="form-group">
      <%= form.label :tag_list, "タグ" %><br>
      <%= form.text_field :tag_list, value: @micropost.tag_list.join(','), class: "form-control border border-primary" %>
    </div>
    <div class="form-group">
      <%= form.submit "更新する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/microposts/index.html.erb
<div class="edit-container">
  <div class="edit-items">
    <% if @q.present? %>
      <h1 class="text-center">作品一覧</h1>

      <%= search_form_for @q do |f| %>
        <div class="form-group">
          <%= f.label :title_cont, "タイトル" %><br>
          <%= f.search_field :title_cont, class: "form-control border border-primary" %>
        <div>
        <div class="form-group">
          <%= f.label :created_at_gteq, '投稿日' %><br>
          <%= f.search_field :created_at_gteq, class: "form-control border border-primary" %>
        </div>
        <div class="form-group">
          <%= f.submit "検索" %>
        </div>
      <% end %>        
    <% else %>
      <h1 class="text-center">タグ一覧</h1>

      <%= form_tag :microposts,method: :get do %>
        <div class="form-group">
          <%= label_tag :tag_name, "タグ検索" %><br>
          <%= text_field_tag "tag_name", '', class: "form-control border border-primary" %>
        </div>
        <div class="form-group">
          <%= submit_tag "検索" %>
        </div>
      <% end %>

      <div class="row col-md-8 mx-auto text-center">
        <div class="mx-auto">
          <% @tags.each do |tag|%>
            <span class="badge badge-pill badge-primary mb-3 mr-3 p-2">
              <%= link_to tag.name, microposts_path(tag_name: tag.name), class: "text-white" %>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div> 
</div>

<div class="conrtainer-fluid">
  <div class="row col-md-8 mx-auto text-center">
    <%= render partial: 'shared/cards', locals: { microposts: @microposts } %>     
  </div>
</div>

app/views/microposts/new.html.erb
<h1 class="text-center">新規投稿</h1>

<div class="edit-container">
  <div class="edit-items">
    <%= form_with model: @micropost, local: true do |form| %>
      <div class="form-group">
        <%= form.label :start_time, "日付" %><br>
        <%= form.datetime_select :start_time %>
      </div>
      <div class="form-group">
        <%= form.label :title, "タイトル" %><br>
        <%= form.text_field :title, class: "form-control border border-primary" %>
      </div>
      <div class="form-group">
        <%= form.label :images, "画像"%><br>
        <%= form.file_field :images, accept: "image/png, image/jpeg, image/gif", class: "form-control border border-primary" %>
      </div>
      <div class="form-group">
        <%= form.label :content, "詳細" %><br>
        <%= form.text_area :content, class: "form-control border border-primary" %>
      </div>
      <div class="form-group">
        <%= form.label :tag_list, "タグ" %><br>
        <%= form.text_field :tag_list, value: @micropost.tag_list.join(','), class: "form-control border border-primary" %>
      </div>
      <div class="form-group">
        <%= form.submit "投稿する" %>
      </div>
    <% end %>
  </div>
</div>

app/views/microposts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <%= render partial: 'shared/user_info', locals: { user: @user } %>
    </div>
    
    <div class="col-md-8">
      <div class="edit-items">
        <% if @micropost.images.attached? %>
          <div>
            <%= image_tag @micropost.images %>
          </div>
        <% end%>
        <div>
          <%= @micropost.title %>
        </div>
        <div>
          <% if current_user.already_liked?(@micropost) %>
            <%= link_to micropost_likes_path(@micropost), method: :delete do %>
            <i class="fas fa-heart", style="color: #ff9aef;"></i>
            <% end%>
          <% else %>
            <%= link_to micropost_likes_path(@micropost), method: :post  do %>
            <i class="far fa-heart", style="color: #ff9aef;"></i>
            <% end %>
          <% end %>
          <%= @micropost.likes.count %>
        </div>
          
        <div>
          <i class="far fa-comment" style="color: #6091d3;"></i>
          <%= @micropost.comments.count %>
        </div>
        <div>
          <%= @micropost.content %>
        </div>
        <% if current_user ==  @micropost.user %>
          <div>
            <%= link_to "編集", edit_micropost_path(@micropost) %>
          </div>
          <div>
            <%= link_to "削除", micropost_path(@micropost), method: :delete %>
          </div>
        <% end %>
        <%= form_for [@micropost, @comment] do |form| %>
          <div class="form-group">
            <%= form.text_field :content, class: "form-control border border-primary" %><br>
            <%= form.submit 'コメントする' %>
          </div>       
        <% end%>
      </div>
    </div>

    <div class="col-md-2">
      <h3>
      <i class="far fa-comment" style="color: #6091d3;"></i>
      コメント一覧
      </h3>
      <div>
        <% @comments.each do |comment| %>
          <p>
          <%= comment.content %><br>
          <%= comment.user.name %>
          <% if current_user == comment.user %>
            <%= link_to "削除", micropost_comment_path(@micropost, comment), method: :delete %>
          <% end%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>