config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  post '/guest_sign_in', to: 'sessions#guest_sign_in'
  get '/signup', to: 'users#new'
  resources :users do
    member do
      get :posts, :liked
    end

    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end

end

app/views/layouts/_header.html.erb
<header class="header-container">
  <% if logged_in? %>
    <div class="menu-wrapper">
      <div class="left-menu-wrapper">
        <div class="menu">
          <%= link_to 'MangAnime', root_path%>
        </div>
        </div>
        <div class="right-menu-wrapper">
          <div class="menu">
            <%= link_to 'ユーザー一覧', users_path %>
          </div>
          <div class="menu">
            <%= link_to '新規投稿', new_micropost_path %>
          </div>
          <div class="menu">
            <%= link_to '投稿一覧', microposts_path %>
          </div>
          <div class="menu">
            <%= link_to 'タグ一覧', microposts_path(tag_name: "#") %>
          </div>
          <div class="menu">
            <%= link_to "マイページ", current_user %>
          </div>
          <div class="menu">
            <%= link_to "ユーザー編集", edit_user_path(current_user) %>
          </div>
          <div class="menu">
            <%= link_to "ログアウト", logout_path, method: :delete %>
          </div>
        </div>
      </div>
  <% else %>
      <div class="menu-wrapper">
        <div class="left-menu-wrapper">
          <div class="menu">
            <%= link_to 'MangAnime', root_path %>
          </div>
        </div>
      </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Copy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="notifications">
      
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
          <%= message %>
          </div>
        <% end %>
      
    </div>
    <%= yield %>
  </body>
</html>